"""change name transformation to transformations in Photo

Revision ID: 24206b709311
Revises: 578b90e4fece
Create Date: 2024-07-04 12:31:30.411588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24206b709311'
down_revision: Union[str, None] = '578b90e4fece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('transformations', sa.JSON(), nullable=True))
    op.drop_column('photos', 'transformation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('transformation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('photos', 'transformations')
    # ### end Alembic commands ###
