"""delete qr_url from Photo

Revision ID: 84419c32b5e0
Revises: 24206b709311
Create Date: 2024-07-14 11:32:49.852863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84419c32b5e0'
down_revision: Union[str, None] = '24206b709311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'qr_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('qr_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
