"""add logout_access_tokens table

Revision ID: 9e16d1e8b2d9
Revises: 228ba19a15f6
Create Date: 2024-05-15 18:43:18.147032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e16d1e8b2d9'
down_revision: Union[str, None] = '228ba19a15f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logout_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logout_access_token', sa.String(length=350), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logout_access_tokens_logout_access_token'), 'logout_access_tokens', ['logout_access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logout_access_tokens_logout_access_token'), table_name='logout_access_tokens')
    op.drop_table('logout_access_tokens')
    # ### end Alembic commands ###
