MAX_DESCRIPTION_LENGTH = 1000
MAX_TAG_NAME_LENGTH = 50
MAX_COMMENT_LENGTH = 1000
MAX_USERNAME_LENGTH = 255

ROLE_ADMIN = "admin"
ROLE_MODERATOR = "moderator"
ROLE_STANDARD = "standard"

API_V1 = "/api/v1"
API = API_V1
AUTH = "/auth"

ACCESS_TOKEN = "access_token"
REFRESH_TOKEN = "refresh_token"

INVALID_SCOPE = "Invalid scope"
COULD_NOT_VALIDATE_CREDENTIALS = "Could not validate credentials"

HTTP_401_UNAUTHORIZED_DETAILS = [INVALID_SCOPE, COULD_NOT_VALIDATE_CREDENTIALS]

TOKEN_NOT_FOUND = "Token not found"

HTTP_404_NOT_FOUND_DETAILS = [TOKEN_NOT_FOUND]

REDIS_EXPIRE = 60 * 15
